# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/debug.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1059, 750)
        self.gridLayout_2 = QtGui.QGridLayout(Form)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.config_groupbox = QtGui.QGroupBox(Form)
        self.config_groupbox.setObjectName(_fromUtf8("config_groupbox"))
        self.gridLayout_9 = QtGui.QGridLayout(self.config_groupbox)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.btn_configure_cam = QtGui.QPushButton(self.config_groupbox)
        self.btn_configure_cam.setObjectName(_fromUtf8("btn_configure_cam"))
        self.gridLayout_8.addWidget(self.btn_configure_cam, 0, 1, 1, 1)
        self.btn_set_reference_plane = QtGui.QPushButton(self.config_groupbox)
        self.btn_set_reference_plane.setObjectName(_fromUtf8("btn_set_reference_plane"))
        self.gridLayout_8.addWidget(self.btn_set_reference_plane, 9, 1, 1, 1)
        self.btn_get_master_gain_range = QtGui.QPushButton(self.config_groupbox)
        self.btn_get_master_gain_range.setObjectName(_fromUtf8("btn_get_master_gain_range"))
        self.gridLayout_8.addWidget(self.btn_get_master_gain_range, 2, 2, 1, 1)
        self.btn_get_exposure_time = QtGui.QPushButton(self.config_groupbox)
        self.btn_get_exposure_time.setObjectName(_fromUtf8("btn_get_exposure_time"))
        self.gridLayout_8.addWidget(self.btn_get_exposure_time, 2, 1, 1, 1)
        self.btn_check_highspeed_centroids = QtGui.QPushButton(self.config_groupbox)
        self.btn_check_highspeed_centroids.setEnabled(False)
        self.btn_check_highspeed_centroids.setObjectName(_fromUtf8("btn_check_highspeed_centroids"))
        self.gridLayout_8.addWidget(self.btn_check_highspeed_centroids, 1, 1, 1, 1)
        self.btn_set_aoi = QtGui.QPushButton(self.config_groupbox)
        self.btn_set_aoi.setObjectName(_fromUtf8("btn_set_aoi"))
        self.gridLayout_8.addWidget(self.btn_set_aoi, 8, 0, 1, 1)
        self.btn_get_reference_plane = QtGui.QPushButton(self.config_groupbox)
        self.btn_get_reference_plane.setObjectName(_fromUtf8("btn_get_reference_plane"))
        self.gridLayout_8.addWidget(self.btn_get_reference_plane, 9, 2, 1, 1)
        self.btn_set_trigger_mode = QtGui.QPushButton(self.config_groupbox)
        self.btn_set_trigger_mode.setObjectName(_fromUtf8("btn_set_trigger_mode"))
        self.gridLayout_8.addWidget(self.btn_set_trigger_mode, 4, 1, 1, 1)
        self.btn_get_mla_data = QtGui.QPushButton(self.config_groupbox)
        self.btn_get_mla_data.setObjectName(_fromUtf8("btn_get_mla_data"))
        self.gridLayout_8.addWidget(self.btn_get_mla_data, 7, 0, 1, 1)
        self.btn_get_trigger_mode = QtGui.QPushButton(self.config_groupbox)
        self.btn_get_trigger_mode.setObjectName(_fromUtf8("btn_get_trigger_mode"))
        self.gridLayout_8.addWidget(self.btn_get_trigger_mode, 4, 2, 1, 1)
        self.btn_set_highspeed_mode = QtGui.QPushButton(self.config_groupbox)
        self.btn_set_highspeed_mode.setEnabled(False)
        self.btn_set_highspeed_mode.setObjectName(_fromUtf8("btn_set_highspeed_mode"))
        self.gridLayout_8.addWidget(self.btn_set_highspeed_mode, 0, 2, 1, 1)
        self.btn_get_mla_data2 = QtGui.QPushButton(self.config_groupbox)
        self.btn_get_mla_data2.setObjectName(_fromUtf8("btn_get_mla_data2"))
        self.gridLayout_8.addWidget(self.btn_get_mla_data2, 7, 1, 1, 1)
        self.btn_get_pupil = QtGui.QPushButton(self.config_groupbox)
        self.btn_get_pupil.setObjectName(_fromUtf8("btn_get_pupil"))
        self.gridLayout_8.addWidget(self.btn_get_pupil, 9, 0, 1, 1)
        self.btn_get_exposure_time_range = QtGui.QPushButton(self.config_groupbox)
        self.btn_get_exposure_time_range.setObjectName(_fromUtf8("btn_get_exposure_time_range"))
        self.gridLayout_8.addWidget(self.btn_get_exposure_time_range, 1, 2, 1, 1)
        self.btn_set_pupil = QtGui.QPushButton(self.config_groupbox)
        self.btn_set_pupil.setObjectName(_fromUtf8("btn_set_pupil"))
        self.gridLayout_8.addWidget(self.btn_set_pupil, 8, 2, 1, 1)
        self.btn_select_mla = QtGui.QPushButton(self.config_groupbox)
        self.btn_select_mla.setObjectName(_fromUtf8("btn_select_mla"))
        self.gridLayout_8.addWidget(self.btn_select_mla, 7, 2, 1, 1)
        self.btn_set_exposure_time = QtGui.QPushButton(self.config_groupbox)
        self.btn_set_exposure_time.setObjectName(_fromUtf8("btn_set_exposure_time"))
        self.gridLayout_8.addWidget(self.btn_set_exposure_time, 2, 0, 1, 1)
        self.btn_get_black_level_offset = QtGui.QPushButton(self.config_groupbox)
        self.btn_get_black_level_offset.setObjectName(_fromUtf8("btn_get_black_level_offset"))
        self.gridLayout_8.addWidget(self.btn_get_black_level_offset, 4, 0, 1, 1)
        self.btn_set_black_level_offset = QtGui.QPushButton(self.config_groupbox)
        self.btn_set_black_level_offset.setObjectName(_fromUtf8("btn_set_black_level_offset"))
        self.gridLayout_8.addWidget(self.btn_set_black_level_offset, 3, 2, 1, 1)
        self.btn_get_aoi = QtGui.QPushButton(self.config_groupbox)
        self.btn_get_aoi.setObjectName(_fromUtf8("btn_get_aoi"))
        self.gridLayout_8.addWidget(self.btn_get_aoi, 8, 1, 1, 1)
        self.btn_get_master_gain = QtGui.QPushButton(self.config_groupbox)
        self.btn_get_master_gain.setObjectName(_fromUtf8("btn_get_master_gain"))
        self.gridLayout_8.addWidget(self.btn_get_master_gain, 3, 1, 1, 1)
        self.btn_get_mla_count = QtGui.QPushButton(self.config_groupbox)
        self.btn_get_mla_count.setObjectName(_fromUtf8("btn_get_mla_count"))
        self.gridLayout_8.addWidget(self.btn_get_mla_count, 5, 2, 1, 1)
        self.btn_get_instrument_info = QtGui.QPushButton(self.config_groupbox)
        self.btn_get_instrument_info.setObjectName(_fromUtf8("btn_get_instrument_info"))
        self.gridLayout_8.addWidget(self.btn_get_instrument_info, 0, 0, 1, 1)
        self.btn_get_highspeed_windows = QtGui.QPushButton(self.config_groupbox)
        self.btn_get_highspeed_windows.setEnabled(False)
        self.btn_get_highspeed_windows.setObjectName(_fromUtf8("btn_get_highspeed_windows"))
        self.gridLayout_8.addWidget(self.btn_get_highspeed_windows, 1, 0, 1, 1)
        self.btn_set_master_gain = QtGui.QPushButton(self.config_groupbox)
        self.btn_set_master_gain.setObjectName(_fromUtf8("btn_set_master_gain"))
        self.gridLayout_8.addWidget(self.btn_set_master_gain, 3, 0, 1, 1)
        self.btn_set_trigger_delay = QtGui.QPushButton(self.config_groupbox)
        self.btn_set_trigger_delay.setObjectName(_fromUtf8("btn_set_trigger_delay"))
        self.gridLayout_8.addWidget(self.btn_set_trigger_delay, 5, 0, 1, 1)
        self.btn_get_trigger_delay_range = QtGui.QPushButton(self.config_groupbox)
        self.btn_get_trigger_delay_range.setObjectName(_fromUtf8("btn_get_trigger_delay_range"))
        self.gridLayout_8.addWidget(self.btn_get_trigger_delay_range, 5, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.config_groupbox, 1, 0, 1, 1)
        self.args_groupbox = QtGui.QGroupBox(Form)
        self.args_groupbox.setObjectName(_fromUtf8("args_groupbox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.args_groupbox)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_arg1 = QtGui.QLabel(self.args_groupbox)
        self.label_arg1.setObjectName(_fromUtf8("label_arg1"))
        self.verticalLayout.addWidget(self.label_arg1)
        self.line_arg1 = QtGui.QLineEdit(self.args_groupbox)
        self.line_arg1.setObjectName(_fromUtf8("line_arg1"))
        self.verticalLayout.addWidget(self.line_arg1)
        self.label_arg2 = QtGui.QLabel(self.args_groupbox)
        self.label_arg2.setObjectName(_fromUtf8("label_arg2"))
        self.verticalLayout.addWidget(self.label_arg2)
        self.line_arg2 = QtGui.QLineEdit(self.args_groupbox)
        self.line_arg2.setObjectName(_fromUtf8("line_arg2"))
        self.verticalLayout.addWidget(self.line_arg2)
        self.label_arg3 = QtGui.QLabel(self.args_groupbox)
        self.label_arg3.setObjectName(_fromUtf8("label_arg3"))
        self.verticalLayout.addWidget(self.label_arg3)
        self.line_arg3 = QtGui.QLineEdit(self.args_groupbox)
        self.line_arg3.setObjectName(_fromUtf8("line_arg3"))
        self.verticalLayout.addWidget(self.line_arg3)
        self.label_arg4 = QtGui.QLabel(self.args_groupbox)
        self.label_arg4.setObjectName(_fromUtf8("label_arg4"))
        self.verticalLayout.addWidget(self.label_arg4)
        self.line_arg4 = QtGui.QLineEdit(self.args_groupbox)
        self.line_arg4.setObjectName(_fromUtf8("line_arg4"))
        self.verticalLayout.addWidget(self.line_arg4)
        self.label_arg5 = QtGui.QLabel(self.args_groupbox)
        self.label_arg5.setObjectName(_fromUtf8("label_arg5"))
        self.verticalLayout.addWidget(self.label_arg5)
        self.line_arg5 = QtGui.QLineEdit(self.args_groupbox)
        self.line_arg5.setObjectName(_fromUtf8("line_arg5"))
        self.verticalLayout.addWidget(self.line_arg5)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addWidget(self.args_groupbox, 6, 0, 1, 1)
        self.utility_groupbox = QtGui.QGroupBox(Form)
        self.utility_groupbox.setObjectName(_fromUtf8("utility_groupbox"))
        self.gridLayout_11 = QtGui.QGridLayout(self.utility_groupbox)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.btn_convert_wavefront_waves = QtGui.QPushButton(self.utility_groupbox)
        self.btn_convert_wavefront_waves.setObjectName(_fromUtf8("btn_convert_wavefront_waves"))
        self.gridLayout_6.addWidget(self.btn_convert_wavefront_waves, 4, 0, 1, 1)
        self.btn_get_xy_scale = QtGui.QPushButton(self.utility_groupbox)
        self.btn_get_xy_scale.setObjectName(_fromUtf8("btn_get_xy_scale"))
        self.gridLayout_6.addWidget(self.btn_get_xy_scale, 3, 1, 1, 1)
        self.btn_error_message = QtGui.QPushButton(self.utility_groupbox)
        self.btn_error_message.setObjectName(_fromUtf8("btn_error_message"))
        self.gridLayout_6.addWidget(self.btn_error_message, 2, 0, 1, 1)
        self.btn_revision_query = QtGui.QPushButton(self.utility_groupbox)
        self.btn_revision_query.setObjectName(_fromUtf8("btn_revision_query"))
        self.gridLayout_6.addWidget(self.btn_revision_query, 1, 0, 1, 1)
        self.btn_reset = QtGui.QPushButton(self.utility_groupbox)
        self.btn_reset.setEnabled(False)
        self.btn_reset.setObjectName(_fromUtf8("btn_reset"))
        self.gridLayout_6.addWidget(self.btn_reset, 0, 1, 1, 1)
        self.btn_self_test = QtGui.QPushButton(self.utility_groupbox)
        self.btn_self_test.setEnabled(False)
        self.btn_self_test.setObjectName(_fromUtf8("btn_self_test"))
        self.gridLayout_6.addWidget(self.btn_self_test, 0, 0, 1, 1)
        self.btn_error_query = QtGui.QPushButton(self.utility_groupbox)
        self.btn_error_query.setEnabled(False)
        self.btn_error_query.setObjectName(_fromUtf8("btn_error_query"))
        self.gridLayout_6.addWidget(self.btn_error_query, 1, 1, 1, 1)
        self.btn_get_instrument_list_info = QtGui.QPushButton(self.utility_groupbox)
        self.btn_get_instrument_list_info.setObjectName(_fromUtf8("btn_get_instrument_list_info"))
        self.gridLayout_6.addWidget(self.btn_get_instrument_list_info, 3, 0, 1, 1)
        self.btn_get_instrument_list_len = QtGui.QPushButton(self.utility_groupbox)
        self.btn_get_instrument_list_len.setObjectName(_fromUtf8("btn_get_instrument_list_len"))
        self.gridLayout_6.addWidget(self.btn_get_instrument_list_len, 2, 1, 1, 1)
        self.btn_flip_2d_array = QtGui.QPushButton(self.utility_groupbox)
        self.btn_flip_2d_array.setObjectName(_fromUtf8("btn_flip_2d_array"))
        self.gridLayout_6.addWidget(self.btn_flip_2d_array, 4, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.utility_groupbox, 2, 0, 1, 1)
        self.data_groupbox = QtGui.QGroupBox(Form)
        self.data_groupbox.setObjectName(_fromUtf8("data_groupbox"))
        self.gridLayout_10 = QtGui.QGridLayout(self.data_groupbox)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.btn_average_image = QtGui.QPushButton(self.data_groupbox)
        self.btn_average_image.setObjectName(_fromUtf8("btn_average_image"))
        self.gridLayout_7.addWidget(self.btn_average_image, 1, 1, 1, 1)
        self.btn_take_spotfield_image = QtGui.QPushButton(self.data_groupbox)
        self.btn_take_spotfield_image.setObjectName(_fromUtf8("btn_take_spotfield_image"))
        self.gridLayout_7.addWidget(self.btn_take_spotfield_image, 0, 0, 1, 1)
        self.btn_average_image_rolling = QtGui.QPushButton(self.data_groupbox)
        self.btn_average_image_rolling.setObjectName(_fromUtf8("btn_average_image_rolling"))
        self.gridLayout_7.addWidget(self.btn_average_image_rolling, 1, 2, 1, 1)
        self.btn_calc_mean_rms_noise = QtGui.QPushButton(self.data_groupbox)
        self.btn_calc_mean_rms_noise.setObjectName(_fromUtf8("btn_calc_mean_rms_noise"))
        self.gridLayout_7.addWidget(self.btn_calc_mean_rms_noise, 2, 2, 1, 1)
        self.btn_zernike_lsf = QtGui.QPushButton(self.data_groupbox)
        self.btn_zernike_lsf.setObjectName(_fromUtf8("btn_zernike_lsf"))
        self.gridLayout_7.addWidget(self.btn_zernike_lsf, 6, 2, 1, 1)
        self.btn_get_spotfield_image_copy = QtGui.QPushButton(self.data_groupbox)
        self.btn_get_spotfield_image_copy.setObjectName(_fromUtf8("btn_get_spotfield_image_copy"))
        self.gridLayout_7.addWidget(self.btn_get_spotfield_image_copy, 1, 0, 1, 1)
        self.btn_cut_image_noise_floor = QtGui.QPushButton(self.data_groupbox)
        self.btn_cut_image_noise_floor.setObjectName(_fromUtf8("btn_cut_image_noise_floor"))
        self.gridLayout_7.addWidget(self.btn_cut_image_noise_floor, 2, 0, 1, 1)
        self.btn_get_line = QtGui.QPushButton(self.data_groupbox)
        self.btn_get_line.setObjectName(_fromUtf8("btn_get_line"))
        self.gridLayout_7.addWidget(self.btn_get_line, 3, 0, 1, 1)
        self.btn_get_spotfield_image = QtGui.QPushButton(self.data_groupbox)
        self.btn_get_spotfield_image.setObjectName(_fromUtf8("btn_get_spotfield_image"))
        self.gridLayout_7.addWidget(self.btn_get_spotfield_image, 0, 2, 1, 1)
        self.btn_calc_spots_centroid_diameter_intensity = QtGui.QPushButton(self.data_groupbox)
        self.btn_calc_spots_centroid_diameter_intensity.setObjectName(_fromUtf8("btn_calc_spots_centroid_diameter_intensity"))
        self.gridLayout_7.addWidget(self.btn_calc_spots_centroid_diameter_intensity, 4, 0, 1, 1)
        self.btn_get_spot_diameters_statistics = QtGui.QPushButton(self.data_groupbox)
        self.btn_get_spot_diameters_statistics.setObjectName(_fromUtf8("btn_get_spot_diameters_statistics"))
        self.gridLayout_7.addWidget(self.btn_get_spot_diameters_statistics, 5, 0, 1, 1)
        self.btn_get_spot_diameters = QtGui.QPushButton(self.data_groupbox)
        self.btn_get_spot_diameters.setObjectName(_fromUtf8("btn_get_spot_diameters"))
        self.gridLayout_7.addWidget(self.btn_get_spot_diameters, 4, 2, 1, 1)
        self.btn_calc_spot_to_reference_deviations = QtGui.QPushButton(self.data_groupbox)
        self.btn_calc_spot_to_reference_deviations.setObjectName(_fromUtf8("btn_calc_spot_to_reference_deviations"))
        self.gridLayout_7.addWidget(self.btn_calc_spot_to_reference_deviations, 5, 2, 1, 1)
        self.btn_get_spot_intensities = QtGui.QPushButton(self.data_groupbox)
        self.btn_get_spot_intensities.setObjectName(_fromUtf8("btn_get_spot_intensities"))
        self.gridLayout_7.addWidget(self.btn_get_spot_intensities, 5, 1, 1, 1)
        self.btn_get_spot_centroids = QtGui.QPushButton(self.data_groupbox)
        self.btn_get_spot_centroids.setObjectName(_fromUtf8("btn_get_spot_centroids"))
        self.gridLayout_7.addWidget(self.btn_get_spot_centroids, 4, 1, 1, 1)
        self.btn_take_spotfield_image_auto_exposure = QtGui.QPushButton(self.data_groupbox)
        self.btn_take_spotfield_image_auto_exposure.setObjectName(_fromUtf8("btn_take_spotfield_image_auto_exposure"))
        self.gridLayout_7.addWidget(self.btn_take_spotfield_image_auto_exposure, 0, 1, 1, 1)
        self.btn_calc_beam_centroid_diameter = QtGui.QPushButton(self.data_groupbox)
        self.btn_calc_beam_centroid_diameter.setObjectName(_fromUtf8("btn_calc_beam_centroid_diameter"))
        self.gridLayout_7.addWidget(self.btn_calc_beam_centroid_diameter, 3, 2, 1, 1)
        self.btn_get_line_view = QtGui.QPushButton(self.data_groupbox)
        self.btn_get_line_view.setObjectName(_fromUtf8("btn_get_line_view"))
        self.gridLayout_7.addWidget(self.btn_get_line_view, 3, 1, 1, 1)
        self.btn_get_spot_reference_positions = QtGui.QPushButton(self.data_groupbox)
        self.btn_get_spot_reference_positions.setObjectName(_fromUtf8("btn_get_spot_reference_positions"))
        self.gridLayout_7.addWidget(self.btn_get_spot_reference_positions, 6, 0, 1, 1)
        self.btn_calc_fourier_optometric = QtGui.QPushButton(self.data_groupbox)
        self.btn_calc_fourier_optometric.setObjectName(_fromUtf8("btn_calc_fourier_optometric"))
        self.gridLayout_7.addWidget(self.btn_calc_fourier_optometric, 7, 0, 1, 1)
        self.btn_calc_wavefront = QtGui.QPushButton(self.data_groupbox)
        self.btn_calc_wavefront.setObjectName(_fromUtf8("btn_calc_wavefront"))
        self.gridLayout_7.addWidget(self.btn_calc_wavefront, 7, 2, 1, 1)
        self.btn_calc_reconstructed_deviations = QtGui.QPushButton(self.data_groupbox)
        self.btn_calc_reconstructed_deviations.setObjectName(_fromUtf8("btn_calc_reconstructed_deviations"))
        self.gridLayout_7.addWidget(self.btn_calc_reconstructed_deviations, 7, 1, 1, 1)
        self.btn_get_spot_deviations = QtGui.QPushButton(self.data_groupbox)
        self.btn_get_spot_deviations.setObjectName(_fromUtf8("btn_get_spot_deviations"))
        self.gridLayout_7.addWidget(self.btn_get_spot_deviations, 6, 1, 1, 1)
        self.btn_calc_image_min_max = QtGui.QPushButton(self.data_groupbox)
        self.btn_calc_image_min_max.setObjectName(_fromUtf8("btn_calc_image_min_max"))
        self.gridLayout_7.addWidget(self.btn_calc_image_min_max, 2, 1, 1, 1)
        self.btn_calc_wavefront_statistics = QtGui.QPushButton(self.data_groupbox)
        self.btn_calc_wavefront_statistics.setObjectName(_fromUtf8("btn_calc_wavefront_statistics"))
        self.gridLayout_7.addWidget(self.btn_calc_wavefront_statistics, 8, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.data_groupbox, 1, 1, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.calibration_groupbox = QtGui.QGroupBox(Form)
        self.calibration_groupbox.setObjectName(_fromUtf8("calibration_groupbox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.calibration_groupbox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btn_set_spots_to_user_reference = QtGui.QPushButton(self.calibration_groupbox)
        self.btn_set_spots_to_user_reference.setObjectName(_fromUtf8("btn_set_spots_to_user_reference"))
        self.gridLayout.addWidget(self.btn_set_spots_to_user_reference, 0, 0, 1, 1)
        self.btn_do_spherical_reference = QtGui.QPushButton(self.calibration_groupbox)
        self.btn_do_spherical_reference.setObjectName(_fromUtf8("btn_do_spherical_reference"))
        self.gridLayout.addWidget(self.btn_do_spherical_reference, 1, 2, 1, 1)
        self.btn_save_user_reference_file = QtGui.QPushButton(self.calibration_groupbox)
        self.btn_save_user_reference_file.setObjectName(_fromUtf8("btn_save_user_reference_file"))
        self.gridLayout.addWidget(self.btn_save_user_reference_file, 1, 0, 1, 1)
        self.btn_create_default_user_reference = QtGui.QPushButton(self.calibration_groupbox)
        self.btn_create_default_user_reference.setObjectName(_fromUtf8("btn_create_default_user_reference"))
        self.gridLayout.addWidget(self.btn_create_default_user_reference, 0, 2, 1, 1)
        self.btn_load_user_reference_file = QtGui.QPushButton(self.calibration_groupbox)
        self.btn_load_user_reference_file.setObjectName(_fromUtf8("btn_load_user_reference_file"))
        self.gridLayout.addWidget(self.btn_load_user_reference_file, 1, 1, 1, 1)
        self.btn_set_calc_spots_to_user_reference = QtGui.QPushButton(self.calibration_groupbox)
        self.btn_set_calc_spots_to_user_reference.setObjectName(_fromUtf8("btn_set_calc_spots_to_user_reference"))
        self.gridLayout.addWidget(self.btn_set_calc_spots_to_user_reference, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.calibration_groupbox)
        self.action_groupbox = QtGui.QGroupBox(Form)
        self.action_groupbox.setObjectName(_fromUtf8("action_groupbox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.action_groupbox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.btn_init = QtGui.QPushButton(self.action_groupbox)
        self.btn_init.setObjectName(_fromUtf8("btn_init"))
        self.gridLayout_4.addWidget(self.btn_init, 0, 0, 1, 1)
        self.btn_close = QtGui.QPushButton(self.action_groupbox)
        self.btn_close.setObjectName(_fromUtf8("btn_close"))
        self.gridLayout_4.addWidget(self.btn_close, 0, 2, 1, 1)
        self.btn_get_status = QtGui.QPushButton(self.action_groupbox)
        self.btn_get_status.setObjectName(_fromUtf8("btn_get_status"))
        self.gridLayout_4.addWidget(self.btn_get_status, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.action_groupbox)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 2, 1, 1, 1)
        self.text_display = QtGui.QTextBrowser(Form)
        self.text_display.setObjectName(_fromUtf8("text_display"))
        self.gridLayout_2.addWidget(self.text_display, 6, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Debug", None))
        self.config_groupbox.setTitle(_translate("Form", "Configuration Functions", None))
        self.btn_configure_cam.setText(_translate("Form", "configure_cam", None))
        self.btn_set_reference_plane.setText(_translate("Form", "set_reference_plane", None))
        self.btn_get_master_gain_range.setText(_translate("Form", "get_master_gain_range", None))
        self.btn_get_exposure_time.setText(_translate("Form", "get_exposure_time", None))
        self.btn_check_highspeed_centroids.setText(_translate("Form", "check_highspeed_centroids", None))
        self.btn_set_aoi.setText(_translate("Form", "set_aoi", None))
        self.btn_get_reference_plane.setText(_translate("Form", "get_reference_plane", None))
        self.btn_set_trigger_mode.setText(_translate("Form", "set_trigger_mode", None))
        self.btn_get_mla_data.setText(_translate("Form", "get_mla_data", None))
        self.btn_get_trigger_mode.setText(_translate("Form", "get_trigger_mode", None))
        self.btn_set_highspeed_mode.setText(_translate("Form", "set_highspeed_mode", None))
        self.btn_get_mla_data2.setText(_translate("Form", "get_mla_data2", None))
        self.btn_get_pupil.setText(_translate("Form", "get_pupil", None))
        self.btn_get_exposure_time_range.setText(_translate("Form", "get_exposure_time_range", None))
        self.btn_set_pupil.setText(_translate("Form", "set_pupil", None))
        self.btn_select_mla.setText(_translate("Form", "select_mla", None))
        self.btn_set_exposure_time.setText(_translate("Form", "set_exposure_time", None))
        self.btn_get_black_level_offset.setText(_translate("Form", "get_black_level_offset", None))
        self.btn_set_black_level_offset.setText(_translate("Form", "set_black_level_offset", None))
        self.btn_get_aoi.setText(_translate("Form", "get_aoi", None))
        self.btn_get_master_gain.setText(_translate("Form", "get_master_gain", None))
        self.btn_get_mla_count.setText(_translate("Form", "get_mla_count", None))
        self.btn_get_instrument_info.setText(_translate("Form", "get_instrument_info", None))
        self.btn_get_highspeed_windows.setText(_translate("Form", "get_highspeed_windows", None))
        self.btn_set_master_gain.setText(_translate("Form", "set_master_gain", None))
        self.btn_set_trigger_delay.setText(_translate("Form", "set_trigger_delay", None))
        self.btn_get_trigger_delay_range.setText(_translate("Form", "get_trigger_delay_range", None))
        self.args_groupbox.setTitle(_translate("Form", "Arguments", None))
        self.label_arg1.setText(_translate("Form", "arg1", None))
        self.label_arg2.setText(_translate("Form", "arg2", None))
        self.label_arg3.setText(_translate("Form", "arg3", None))
        self.label_arg4.setText(_translate("Form", "arg4", None))
        self.label_arg5.setText(_translate("Form", "arg5 (instrument_handle)", None))
        self.utility_groupbox.setTitle(_translate("Form", "Utility Functions", None))
        self.btn_convert_wavefront_waves.setText(_translate("Form", "convert_wavefront_waves", None))
        self.btn_get_xy_scale.setText(_translate("Form", "get_xy_scale", None))
        self.btn_error_message.setText(_translate("Form", "error_message", None))
        self.btn_revision_query.setText(_translate("Form", "revision_query", None))
        self.btn_reset.setText(_translate("Form", "reset", None))
        self.btn_self_test.setText(_translate("Form", "self_test", None))
        self.btn_error_query.setText(_translate("Form", "error_query", None))
        self.btn_get_instrument_list_info.setText(_translate("Form", "get_instrument_list_info", None))
        self.btn_get_instrument_list_len.setText(_translate("Form", "get_instrument_list_len", None))
        self.btn_flip_2d_array.setText(_translate("Form", "flip_2d_array", None))
        self.data_groupbox.setTitle(_translate("Form", "Data Functions", None))
        self.btn_average_image.setText(_translate("Form", "average_image", None))
        self.btn_take_spotfield_image.setText(_translate("Form", "take_spotfield_image", None))
        self.btn_average_image_rolling.setText(_translate("Form", "average_image_rolling", None))
        self.btn_calc_mean_rms_noise.setText(_translate("Form", "calc_mean_rms_noise", None))
        self.btn_zernike_lsf.setText(_translate("Form", "zernike_lsf", None))
        self.btn_get_spotfield_image_copy.setText(_translate("Form", "get_spotfield_image_copy", None))
        self.btn_cut_image_noise_floor.setText(_translate("Form", "cut_image_noise_floor", None))
        self.btn_get_line.setText(_translate("Form", "get_line", None))
        self.btn_get_spotfield_image.setText(_translate("Form", "get_spotfield_image", None))
        self.btn_calc_spots_centroid_diameter_intensity.setText(_translate("Form", "calc_spots_centroid_diameter_intensity", None))
        self.btn_get_spot_diameters_statistics.setText(_translate("Form", "get_spot_diameters_statistics", None))
        self.btn_get_spot_diameters.setText(_translate("Form", "get_spot_diameters", None))
        self.btn_calc_spot_to_reference_deviations.setText(_translate("Form", "calc_spot_to_reference_deviations", None))
        self.btn_get_spot_intensities.setText(_translate("Form", "get_spot_intensities", None))
        self.btn_get_spot_centroids.setText(_translate("Form", "get_spot_centroids", None))
        self.btn_take_spotfield_image_auto_exposure.setText(_translate("Form", "take_spotfield_image_auto_exposure", None))
        self.btn_calc_beam_centroid_diameter.setText(_translate("Form", "calc_beam_centroid_diameter", None))
        self.btn_get_line_view.setText(_translate("Form", "get_line_view", None))
        self.btn_get_spot_reference_positions.setText(_translate("Form", "get_spot_reference_positions", None))
        self.btn_calc_fourier_optometric.setText(_translate("Form", "calc_fourier_optometric", None))
        self.btn_calc_wavefront.setText(_translate("Form", "calc_wavefront", None))
        self.btn_calc_reconstructed_deviations.setText(_translate("Form", "calc_reconstructed_deviations", None))
        self.btn_get_spot_deviations.setText(_translate("Form", "get_spot_deviations", None))
        self.btn_calc_image_min_max.setText(_translate("Form", "_calc_image_min_max", None))
        self.btn_calc_wavefront_statistics.setText(_translate("Form", "calc_wavefront_statistics", None))
        self.calibration_groupbox.setTitle(_translate("Form", "Calibration Functions", None))
        self.btn_set_spots_to_user_reference.setText(_translate("Form", "set_spots_to_user_reference", None))
        self.btn_do_spherical_reference.setText(_translate("Form", "do_spherical_reference", None))
        self.btn_save_user_reference_file.setText(_translate("Form", "save_user_reference_file", None))
        self.btn_create_default_user_reference.setText(_translate("Form", "create_default_user_reference", None))
        self.btn_load_user_reference_file.setText(_translate("Form", "load_user_reference_file", None))
        self.btn_set_calc_spots_to_user_reference.setText(_translate("Form", "set_calc_spots_to_user_reference", None))
        self.action_groupbox.setTitle(_translate("Form", "Action Functions", None))
        self.btn_init.setText(_translate("Form", "init", None))
        self.btn_close.setText(_translate("Form", "close", None))
        self.btn_get_status.setText(_translate("Form", "get_status", None))

