# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/debug.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1059, 750)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.config_groupbox = QtWidgets.QGroupBox(Form)
        self.config_groupbox.setObjectName("config_groupbox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.config_groupbox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.btn_configure_cam = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_configure_cam.setObjectName("btn_configure_cam")
        self.gridLayout_8.addWidget(self.btn_configure_cam, 0, 1, 1, 1)
        self.btn_set_reference_plane = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_set_reference_plane.setObjectName("btn_set_reference_plane")
        self.gridLayout_8.addWidget(self.btn_set_reference_plane, 9, 1, 1, 1)
        self.btn_get_master_gain_range = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_get_master_gain_range.setObjectName("btn_get_master_gain_range")
        self.gridLayout_8.addWidget(self.btn_get_master_gain_range, 2, 2, 1, 1)
        self.btn_get_exposure_time = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_get_exposure_time.setObjectName("btn_get_exposure_time")
        self.gridLayout_8.addWidget(self.btn_get_exposure_time, 2, 1, 1, 1)
        self.btn_check_highspeed_centroids = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_check_highspeed_centroids.setEnabled(False)
        self.btn_check_highspeed_centroids.setObjectName("btn_check_highspeed_centroids")
        self.gridLayout_8.addWidget(self.btn_check_highspeed_centroids, 1, 1, 1, 1)
        self.btn_set_aoi = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_set_aoi.setObjectName("btn_set_aoi")
        self.gridLayout_8.addWidget(self.btn_set_aoi, 8, 0, 1, 1)
        self.btn_get_reference_plane = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_get_reference_plane.setObjectName("btn_get_reference_plane")
        self.gridLayout_8.addWidget(self.btn_get_reference_plane, 9, 2, 1, 1)
        self.btn_set_trigger_mode = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_set_trigger_mode.setObjectName("btn_set_trigger_mode")
        self.gridLayout_8.addWidget(self.btn_set_trigger_mode, 4, 1, 1, 1)
        self.btn_get_mla_data = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_get_mla_data.setObjectName("btn_get_mla_data")
        self.gridLayout_8.addWidget(self.btn_get_mla_data, 7, 0, 1, 1)
        self.btn_get_trigger_mode = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_get_trigger_mode.setObjectName("btn_get_trigger_mode")
        self.gridLayout_8.addWidget(self.btn_get_trigger_mode, 4, 2, 1, 1)
        self.btn_set_highspeed_mode = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_set_highspeed_mode.setEnabled(False)
        self.btn_set_highspeed_mode.setObjectName("btn_set_highspeed_mode")
        self.gridLayout_8.addWidget(self.btn_set_highspeed_mode, 0, 2, 1, 1)
        self.btn_get_mla_data2 = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_get_mla_data2.setObjectName("btn_get_mla_data2")
        self.gridLayout_8.addWidget(self.btn_get_mla_data2, 7, 1, 1, 1)
        self.btn_get_pupil = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_get_pupil.setObjectName("btn_get_pupil")
        self.gridLayout_8.addWidget(self.btn_get_pupil, 9, 0, 1, 1)
        self.btn_get_exposure_time_range = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_get_exposure_time_range.setObjectName("btn_get_exposure_time_range")
        self.gridLayout_8.addWidget(self.btn_get_exposure_time_range, 1, 2, 1, 1)
        self.btn_set_pupil = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_set_pupil.setObjectName("btn_set_pupil")
        self.gridLayout_8.addWidget(self.btn_set_pupil, 8, 2, 1, 1)
        self.btn_select_mla = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_select_mla.setObjectName("btn_select_mla")
        self.gridLayout_8.addWidget(self.btn_select_mla, 7, 2, 1, 1)
        self.btn_set_exposure_time = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_set_exposure_time.setObjectName("btn_set_exposure_time")
        self.gridLayout_8.addWidget(self.btn_set_exposure_time, 2, 0, 1, 1)
        self.btn_get_black_level_offset = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_get_black_level_offset.setObjectName("btn_get_black_level_offset")
        self.gridLayout_8.addWidget(self.btn_get_black_level_offset, 4, 0, 1, 1)
        self.btn_set_black_level_offset = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_set_black_level_offset.setObjectName("btn_set_black_level_offset")
        self.gridLayout_8.addWidget(self.btn_set_black_level_offset, 3, 2, 1, 1)
        self.btn_get_aoi = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_get_aoi.setObjectName("btn_get_aoi")
        self.gridLayout_8.addWidget(self.btn_get_aoi, 8, 1, 1, 1)
        self.btn_get_master_gain = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_get_master_gain.setObjectName("btn_get_master_gain")
        self.gridLayout_8.addWidget(self.btn_get_master_gain, 3, 1, 1, 1)
        self.btn_get_mla_count = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_get_mla_count.setObjectName("btn_get_mla_count")
        self.gridLayout_8.addWidget(self.btn_get_mla_count, 5, 2, 1, 1)
        self.btn_get_instrument_info = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_get_instrument_info.setObjectName("btn_get_instrument_info")
        self.gridLayout_8.addWidget(self.btn_get_instrument_info, 0, 0, 1, 1)
        self.btn_get_highspeed_windows = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_get_highspeed_windows.setEnabled(False)
        self.btn_get_highspeed_windows.setObjectName("btn_get_highspeed_windows")
        self.gridLayout_8.addWidget(self.btn_get_highspeed_windows, 1, 0, 1, 1)
        self.btn_set_master_gain = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_set_master_gain.setObjectName("btn_set_master_gain")
        self.gridLayout_8.addWidget(self.btn_set_master_gain, 3, 0, 1, 1)
        self.btn_set_trigger_delay = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_set_trigger_delay.setObjectName("btn_set_trigger_delay")
        self.gridLayout_8.addWidget(self.btn_set_trigger_delay, 5, 0, 1, 1)
        self.btn_get_trigger_delay_range = QtWidgets.QPushButton(self.config_groupbox)
        self.btn_get_trigger_delay_range.setObjectName("btn_get_trigger_delay_range")
        self.gridLayout_8.addWidget(self.btn_get_trigger_delay_range, 5, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.config_groupbox, 1, 0, 1, 1)
        self.args_groupbox = QtWidgets.QGroupBox(Form)
        self.args_groupbox.setObjectName("args_groupbox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.args_groupbox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_arg1 = QtWidgets.QLabel(self.args_groupbox)
        self.label_arg1.setObjectName("label_arg1")
        self.verticalLayout.addWidget(self.label_arg1)
        self.line_arg1 = QtWidgets.QLineEdit(self.args_groupbox)
        self.line_arg1.setObjectName("line_arg1")
        self.verticalLayout.addWidget(self.line_arg1)
        self.label_arg2 = QtWidgets.QLabel(self.args_groupbox)
        self.label_arg2.setObjectName("label_arg2")
        self.verticalLayout.addWidget(self.label_arg2)
        self.line_arg2 = QtWidgets.QLineEdit(self.args_groupbox)
        self.line_arg2.setObjectName("line_arg2")
        self.verticalLayout.addWidget(self.line_arg2)
        self.label_arg3 = QtWidgets.QLabel(self.args_groupbox)
        self.label_arg3.setObjectName("label_arg3")
        self.verticalLayout.addWidget(self.label_arg3)
        self.line_arg3 = QtWidgets.QLineEdit(self.args_groupbox)
        self.line_arg3.setObjectName("line_arg3")
        self.verticalLayout.addWidget(self.line_arg3)
        self.label_arg4 = QtWidgets.QLabel(self.args_groupbox)
        self.label_arg4.setObjectName("label_arg4")
        self.verticalLayout.addWidget(self.label_arg4)
        self.line_arg4 = QtWidgets.QLineEdit(self.args_groupbox)
        self.line_arg4.setObjectName("line_arg4")
        self.verticalLayout.addWidget(self.line_arg4)
        self.label_arg5 = QtWidgets.QLabel(self.args_groupbox)
        self.label_arg5.setObjectName("label_arg5")
        self.verticalLayout.addWidget(self.label_arg5)
        self.line_arg5 = QtWidgets.QLineEdit(self.args_groupbox)
        self.line_arg5.setObjectName("line_arg5")
        self.verticalLayout.addWidget(self.line_arg5)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addWidget(self.args_groupbox, 6, 0, 1, 1)
        self.utility_groupbox = QtWidgets.QGroupBox(Form)
        self.utility_groupbox.setObjectName("utility_groupbox")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.utility_groupbox)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.btn_convert_wavefront_waves = QtWidgets.QPushButton(self.utility_groupbox)
        self.btn_convert_wavefront_waves.setObjectName("btn_convert_wavefront_waves")
        self.gridLayout_6.addWidget(self.btn_convert_wavefront_waves, 4, 0, 1, 1)
        self.btn_get_xy_scale = QtWidgets.QPushButton(self.utility_groupbox)
        self.btn_get_xy_scale.setObjectName("btn_get_xy_scale")
        self.gridLayout_6.addWidget(self.btn_get_xy_scale, 3, 1, 1, 1)
        self.btn_error_message = QtWidgets.QPushButton(self.utility_groupbox)
        self.btn_error_message.setObjectName("btn_error_message")
        self.gridLayout_6.addWidget(self.btn_error_message, 2, 0, 1, 1)
        self.btn_revision_query = QtWidgets.QPushButton(self.utility_groupbox)
        self.btn_revision_query.setObjectName("btn_revision_query")
        self.gridLayout_6.addWidget(self.btn_revision_query, 1, 0, 1, 1)
        self.btn_reset = QtWidgets.QPushButton(self.utility_groupbox)
        self.btn_reset.setEnabled(False)
        self.btn_reset.setObjectName("btn_reset")
        self.gridLayout_6.addWidget(self.btn_reset, 0, 1, 1, 1)
        self.btn_self_test = QtWidgets.QPushButton(self.utility_groupbox)
        self.btn_self_test.setEnabled(False)
        self.btn_self_test.setObjectName("btn_self_test")
        self.gridLayout_6.addWidget(self.btn_self_test, 0, 0, 1, 1)
        self.btn_error_query = QtWidgets.QPushButton(self.utility_groupbox)
        self.btn_error_query.setEnabled(False)
        self.btn_error_query.setObjectName("btn_error_query")
        self.gridLayout_6.addWidget(self.btn_error_query, 1, 1, 1, 1)
        self.btn_get_instrument_list_info = QtWidgets.QPushButton(self.utility_groupbox)
        self.btn_get_instrument_list_info.setObjectName("btn_get_instrument_list_info")
        self.gridLayout_6.addWidget(self.btn_get_instrument_list_info, 3, 0, 1, 1)
        self.btn_get_instrument_list_len = QtWidgets.QPushButton(self.utility_groupbox)
        self.btn_get_instrument_list_len.setObjectName("btn_get_instrument_list_len")
        self.gridLayout_6.addWidget(self.btn_get_instrument_list_len, 2, 1, 1, 1)
        self.btn_flip_2d_array = QtWidgets.QPushButton(self.utility_groupbox)
        self.btn_flip_2d_array.setObjectName("btn_flip_2d_array")
        self.gridLayout_6.addWidget(self.btn_flip_2d_array, 4, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.utility_groupbox, 2, 0, 1, 1)
        self.data_groupbox = QtWidgets.QGroupBox(Form)
        self.data_groupbox.setObjectName("data_groupbox")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.data_groupbox)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.btn_average_image = QtWidgets.QPushButton(self.data_groupbox)
        self.btn_average_image.setObjectName("btn_average_image")
        self.gridLayout_7.addWidget(self.btn_average_image, 1, 1, 1, 1)
        self.btn_take_spotfield_image = QtWidgets.QPushButton(self.data_groupbox)
        self.btn_take_spotfield_image.setObjectName("btn_take_spotfield_image")
        self.gridLayout_7.addWidget(self.btn_take_spotfield_image, 0, 0, 1, 1)
        self.btn_average_image_rolling = QtWidgets.QPushButton(self.data_groupbox)
        self.btn_average_image_rolling.setObjectName("btn_average_image_rolling")
        self.gridLayout_7.addWidget(self.btn_average_image_rolling, 1, 2, 1, 1)
        self.btn_calc_mean_rms_noise = QtWidgets.QPushButton(self.data_groupbox)
        self.btn_calc_mean_rms_noise.setObjectName("btn_calc_mean_rms_noise")
        self.gridLayout_7.addWidget(self.btn_calc_mean_rms_noise, 2, 2, 1, 1)
        self.btn_zernike_lsf = QtWidgets.QPushButton(self.data_groupbox)
        self.btn_zernike_lsf.setObjectName("btn_zernike_lsf")
        self.gridLayout_7.addWidget(self.btn_zernike_lsf, 6, 2, 1, 1)
        self.btn_get_spotfield_image_copy = QtWidgets.QPushButton(self.data_groupbox)
        self.btn_get_spotfield_image_copy.setObjectName("btn_get_spotfield_image_copy")
        self.gridLayout_7.addWidget(self.btn_get_spotfield_image_copy, 1, 0, 1, 1)
        self.btn_cut_image_noise_floor = QtWidgets.QPushButton(self.data_groupbox)
        self.btn_cut_image_noise_floor.setObjectName("btn_cut_image_noise_floor")
        self.gridLayout_7.addWidget(self.btn_cut_image_noise_floor, 2, 0, 1, 1)
        self.btn_get_line = QtWidgets.QPushButton(self.data_groupbox)
        self.btn_get_line.setObjectName("btn_get_line")
        self.gridLayout_7.addWidget(self.btn_get_line, 3, 0, 1, 1)
        self.btn_get_spotfield_image = QtWidgets.QPushButton(self.data_groupbox)
        self.btn_get_spotfield_image.setObjectName("btn_get_spotfield_image")
        self.gridLayout_7.addWidget(self.btn_get_spotfield_image, 0, 2, 1, 1)
        self.btn_calc_spots_centroid_diameter_intensity = QtWidgets.QPushButton(self.data_groupbox)
        self.btn_calc_spots_centroid_diameter_intensity.setObjectName("btn_calc_spots_centroid_diameter_intensity")
        self.gridLayout_7.addWidget(self.btn_calc_spots_centroid_diameter_intensity, 4, 0, 1, 1)
        self.btn_get_spot_diameters_statistics = QtWidgets.QPushButton(self.data_groupbox)
        self.btn_get_spot_diameters_statistics.setObjectName("btn_get_spot_diameters_statistics")
        self.gridLayout_7.addWidget(self.btn_get_spot_diameters_statistics, 5, 0, 1, 1)
        self.btn_get_spot_diameters = QtWidgets.QPushButton(self.data_groupbox)
        self.btn_get_spot_diameters.setObjectName("btn_get_spot_diameters")
        self.gridLayout_7.addWidget(self.btn_get_spot_diameters, 4, 2, 1, 1)
        self.btn_calc_spot_to_reference_deviations = QtWidgets.QPushButton(self.data_groupbox)
        self.btn_calc_spot_to_reference_deviations.setObjectName("btn_calc_spot_to_reference_deviations")
        self.gridLayout_7.addWidget(self.btn_calc_spot_to_reference_deviations, 5, 2, 1, 1)
        self.btn_get_spot_intensities = QtWidgets.QPushButton(self.data_groupbox)
        self.btn_get_spot_intensities.setObjectName("btn_get_spot_intensities")
        self.gridLayout_7.addWidget(self.btn_get_spot_intensities, 5, 1, 1, 1)
        self.btn_get_spot_centroids = QtWidgets.QPushButton(self.data_groupbox)
        self.btn_get_spot_centroids.setObjectName("btn_get_spot_centroids")
        self.gridLayout_7.addWidget(self.btn_get_spot_centroids, 4, 1, 1, 1)
        self.btn_take_spotfield_image_auto_exposure = QtWidgets.QPushButton(self.data_groupbox)
        self.btn_take_spotfield_image_auto_exposure.setObjectName("btn_take_spotfield_image_auto_exposure")
        self.gridLayout_7.addWidget(self.btn_take_spotfield_image_auto_exposure, 0, 1, 1, 1)
        self.btn_calc_beam_centroid_diameter = QtWidgets.QPushButton(self.data_groupbox)
        self.btn_calc_beam_centroid_diameter.setObjectName("btn_calc_beam_centroid_diameter")
        self.gridLayout_7.addWidget(self.btn_calc_beam_centroid_diameter, 3, 2, 1, 1)
        self.btn_get_line_view = QtWidgets.QPushButton(self.data_groupbox)
        self.btn_get_line_view.setObjectName("btn_get_line_view")
        self.gridLayout_7.addWidget(self.btn_get_line_view, 3, 1, 1, 1)
        self.btn_get_spot_reference_positions = QtWidgets.QPushButton(self.data_groupbox)
        self.btn_get_spot_reference_positions.setObjectName("btn_get_spot_reference_positions")
        self.gridLayout_7.addWidget(self.btn_get_spot_reference_positions, 6, 0, 1, 1)
        self.btn_calc_fourier_optometric = QtWidgets.QPushButton(self.data_groupbox)
        self.btn_calc_fourier_optometric.setObjectName("btn_calc_fourier_optometric")
        self.gridLayout_7.addWidget(self.btn_calc_fourier_optometric, 7, 0, 1, 1)
        self.btn_calc_wavefront = QtWidgets.QPushButton(self.data_groupbox)
        self.btn_calc_wavefront.setObjectName("btn_calc_wavefront")
        self.gridLayout_7.addWidget(self.btn_calc_wavefront, 7, 2, 1, 1)
        self.btn_calc_reconstructed_deviations = QtWidgets.QPushButton(self.data_groupbox)
        self.btn_calc_reconstructed_deviations.setObjectName("btn_calc_reconstructed_deviations")
        self.gridLayout_7.addWidget(self.btn_calc_reconstructed_deviations, 7, 1, 1, 1)
        self.btn_get_spot_deviations = QtWidgets.QPushButton(self.data_groupbox)
        self.btn_get_spot_deviations.setObjectName("btn_get_spot_deviations")
        self.gridLayout_7.addWidget(self.btn_get_spot_deviations, 6, 1, 1, 1)
        self.btn_calc_image_min_max = QtWidgets.QPushButton(self.data_groupbox)
        self.btn_calc_image_min_max.setObjectName("btn_calc_image_min_max")
        self.gridLayout_7.addWidget(self.btn_calc_image_min_max, 2, 1, 1, 1)
        self.btn_calc_wavefront_statistics = QtWidgets.QPushButton(self.data_groupbox)
        self.btn_calc_wavefront_statistics.setObjectName("btn_calc_wavefront_statistics")
        self.gridLayout_7.addWidget(self.btn_calc_wavefront_statistics, 8, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.data_groupbox, 1, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.calibration_groupbox = QtWidgets.QGroupBox(Form)
        self.calibration_groupbox.setObjectName("calibration_groupbox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.calibration_groupbox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_set_spots_to_user_reference = QtWidgets.QPushButton(self.calibration_groupbox)
        self.btn_set_spots_to_user_reference.setObjectName("btn_set_spots_to_user_reference")
        self.gridLayout.addWidget(self.btn_set_spots_to_user_reference, 0, 0, 1, 1)
        self.btn_do_spherical_reference = QtWidgets.QPushButton(self.calibration_groupbox)
        self.btn_do_spherical_reference.setObjectName("btn_do_spherical_reference")
        self.gridLayout.addWidget(self.btn_do_spherical_reference, 1, 2, 1, 1)
        self.btn_save_user_reference_file = QtWidgets.QPushButton(self.calibration_groupbox)
        self.btn_save_user_reference_file.setObjectName("btn_save_user_reference_file")
        self.gridLayout.addWidget(self.btn_save_user_reference_file, 1, 0, 1, 1)
        self.btn_create_default_user_reference = QtWidgets.QPushButton(self.calibration_groupbox)
        self.btn_create_default_user_reference.setObjectName("btn_create_default_user_reference")
        self.gridLayout.addWidget(self.btn_create_default_user_reference, 0, 2, 1, 1)
        self.btn_load_user_reference_file = QtWidgets.QPushButton(self.calibration_groupbox)
        self.btn_load_user_reference_file.setObjectName("btn_load_user_reference_file")
        self.gridLayout.addWidget(self.btn_load_user_reference_file, 1, 1, 1, 1)
        self.btn_set_calc_spots_to_user_reference = QtWidgets.QPushButton(self.calibration_groupbox)
        self.btn_set_calc_spots_to_user_reference.setObjectName("btn_set_calc_spots_to_user_reference")
        self.gridLayout.addWidget(self.btn_set_calc_spots_to_user_reference, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.calibration_groupbox)
        self.action_groupbox = QtWidgets.QGroupBox(Form)
        self.action_groupbox.setObjectName("action_groupbox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.action_groupbox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btn_init = QtWidgets.QPushButton(self.action_groupbox)
        self.btn_init.setObjectName("btn_init")
        self.gridLayout_4.addWidget(self.btn_init, 0, 0, 1, 1)
        self.btn_close = QtWidgets.QPushButton(self.action_groupbox)
        self.btn_close.setObjectName("btn_close")
        self.gridLayout_4.addWidget(self.btn_close, 0, 2, 1, 1)
        self.btn_get_status = QtWidgets.QPushButton(self.action_groupbox)
        self.btn_get_status.setObjectName("btn_get_status")
        self.gridLayout_4.addWidget(self.btn_get_status, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.action_groupbox)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 2, 1, 1, 1)
        self.text_display = QtWidgets.QTextBrowser(Form)
        self.text_display.setObjectName("text_display")
        self.gridLayout_2.addWidget(self.text_display, 6, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Debug"))
        self.config_groupbox.setTitle(_translate("Form", "Configuration Functions"))
        self.btn_configure_cam.setText(_translate("Form", "configure_cam"))
        self.btn_set_reference_plane.setText(_translate("Form", "set_reference_plane"))
        self.btn_get_master_gain_range.setText(_translate("Form", "get_master_gain_range"))
        self.btn_get_exposure_time.setText(_translate("Form", "get_exposure_time"))
        self.btn_check_highspeed_centroids.setText(_translate("Form", "check_highspeed_centroids"))
        self.btn_set_aoi.setText(_translate("Form", "set_aoi"))
        self.btn_get_reference_plane.setText(_translate("Form", "get_reference_plane"))
        self.btn_set_trigger_mode.setText(_translate("Form", "set_trigger_mode"))
        self.btn_get_mla_data.setText(_translate("Form", "get_mla_data"))
        self.btn_get_trigger_mode.setText(_translate("Form", "get_trigger_mode"))
        self.btn_set_highspeed_mode.setText(_translate("Form", "set_highspeed_mode"))
        self.btn_get_mla_data2.setText(_translate("Form", "get_mla_data2"))
        self.btn_get_pupil.setText(_translate("Form", "get_pupil"))
        self.btn_get_exposure_time_range.setText(_translate("Form", "get_exposure_time_range"))
        self.btn_set_pupil.setText(_translate("Form", "set_pupil"))
        self.btn_select_mla.setText(_translate("Form", "select_mla"))
        self.btn_set_exposure_time.setText(_translate("Form", "set_exposure_time"))
        self.btn_get_black_level_offset.setText(_translate("Form", "get_black_level_offset"))
        self.btn_set_black_level_offset.setText(_translate("Form", "set_black_level_offset"))
        self.btn_get_aoi.setText(_translate("Form", "get_aoi"))
        self.btn_get_master_gain.setText(_translate("Form", "get_master_gain"))
        self.btn_get_mla_count.setText(_translate("Form", "get_mla_count"))
        self.btn_get_instrument_info.setText(_translate("Form", "get_instrument_info"))
        self.btn_get_highspeed_windows.setText(_translate("Form", "get_highspeed_windows"))
        self.btn_set_master_gain.setText(_translate("Form", "set_master_gain"))
        self.btn_set_trigger_delay.setText(_translate("Form", "set_trigger_delay"))
        self.btn_get_trigger_delay_range.setText(_translate("Form", "get_trigger_delay_range"))
        self.args_groupbox.setTitle(_translate("Form", "Arguments"))
        self.label_arg1.setText(_translate("Form", "arg1"))
        self.label_arg2.setText(_translate("Form", "arg2"))
        self.label_arg3.setText(_translate("Form", "arg3"))
        self.label_arg4.setText(_translate("Form", "arg4"))
        self.label_arg5.setText(_translate("Form", "arg5 (instrument_handle)"))
        self.utility_groupbox.setTitle(_translate("Form", "Utility Functions"))
        self.btn_convert_wavefront_waves.setText(_translate("Form", "convert_wavefront_waves"))
        self.btn_get_xy_scale.setText(_translate("Form", "get_xy_scale"))
        self.btn_error_message.setText(_translate("Form", "error_message"))
        self.btn_revision_query.setText(_translate("Form", "revision_query"))
        self.btn_reset.setText(_translate("Form", "reset"))
        self.btn_self_test.setText(_translate("Form", "self_test"))
        self.btn_error_query.setText(_translate("Form", "error_query"))
        self.btn_get_instrument_list_info.setText(_translate("Form", "get_instrument_list_info"))
        self.btn_get_instrument_list_len.setText(_translate("Form", "get_instrument_list_len"))
        self.btn_flip_2d_array.setText(_translate("Form", "flip_2d_array"))
        self.data_groupbox.setTitle(_translate("Form", "Data Functions"))
        self.btn_average_image.setText(_translate("Form", "average_image"))
        self.btn_take_spotfield_image.setText(_translate("Form", "take_spotfield_image"))
        self.btn_average_image_rolling.setText(_translate("Form", "average_image_rolling"))
        self.btn_calc_mean_rms_noise.setText(_translate("Form", "calc_mean_rms_noise"))
        self.btn_zernike_lsf.setText(_translate("Form", "zernike_lsf"))
        self.btn_get_spotfield_image_copy.setText(_translate("Form", "get_spotfield_image_copy"))
        self.btn_cut_image_noise_floor.setText(_translate("Form", "cut_image_noise_floor"))
        self.btn_get_line.setText(_translate("Form", "get_line"))
        self.btn_get_spotfield_image.setText(_translate("Form", "get_spotfield_image"))
        self.btn_calc_spots_centroid_diameter_intensity.setText(_translate("Form", "calc_spots_centroid_diameter_intensity"))
        self.btn_get_spot_diameters_statistics.setText(_translate("Form", "get_spot_diameters_statistics"))
        self.btn_get_spot_diameters.setText(_translate("Form", "get_spot_diameters"))
        self.btn_calc_spot_to_reference_deviations.setText(_translate("Form", "calc_spot_to_reference_deviations"))
        self.btn_get_spot_intensities.setText(_translate("Form", "get_spot_intensities"))
        self.btn_get_spot_centroids.setText(_translate("Form", "get_spot_centroids"))
        self.btn_take_spotfield_image_auto_exposure.setText(_translate("Form", "take_spotfield_image_auto_exposure"))
        self.btn_calc_beam_centroid_diameter.setText(_translate("Form", "calc_beam_centroid_diameter"))
        self.btn_get_line_view.setText(_translate("Form", "get_line_view"))
        self.btn_get_spot_reference_positions.setText(_translate("Form", "get_spot_reference_positions"))
        self.btn_calc_fourier_optometric.setText(_translate("Form", "calc_fourier_optometric"))
        self.btn_calc_wavefront.setText(_translate("Form", "calc_wavefront"))
        self.btn_calc_reconstructed_deviations.setText(_translate("Form", "calc_reconstructed_deviations"))
        self.btn_get_spot_deviations.setText(_translate("Form", "get_spot_deviations"))
        self.btn_calc_image_min_max.setText(_translate("Form", "_calc_image_min_max"))
        self.btn_calc_wavefront_statistics.setText(_translate("Form", "calc_wavefront_statistics"))
        self.calibration_groupbox.setTitle(_translate("Form", "Calibration Functions"))
        self.btn_set_spots_to_user_reference.setText(_translate("Form", "set_spots_to_user_reference"))
        self.btn_do_spherical_reference.setText(_translate("Form", "do_spherical_reference"))
        self.btn_save_user_reference_file.setText(_translate("Form", "save_user_reference_file"))
        self.btn_create_default_user_reference.setText(_translate("Form", "create_default_user_reference"))
        self.btn_load_user_reference_file.setText(_translate("Form", "load_user_reference_file"))
        self.btn_set_calc_spots_to_user_reference.setText(_translate("Form", "set_calc_spots_to_user_reference"))
        self.action_groupbox.setTitle(_translate("Form", "Action Functions"))
        self.btn_init.setText(_translate("Form", "init"))
        self.btn_close.setText(_translate("Form", "close"))
        self.btn_get_status.setText(_translate("Form", "get_status"))

