# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Workspace\Code\wfs\gui\design.ui'
#
# Created: Mon Mar 14 10:53:41 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(555, 541)
        self.centralwidget = QtGui.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.group_box = QtGui.QGroupBox(self.centralwidget)
        self.group_box.setObjectName("group_box")
        self.gridLayout_2 = QtGui.QGridLayout(self.group_box)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_debug = QtGui.QPushButton(self.group_box)
        self.btn_debug.setObjectName("btn_debug")
        self.gridLayout_2.addWidget(self.btn_debug, 0, 2, 1, 1)
        self.btn_settings = QtGui.QPushButton(self.group_box)
        self.btn_settings.setObjectName("btn_settings")
        self.gridLayout_2.addWidget(self.btn_settings, 0, 0, 1, 1)
        self.btn_test = QtGui.QPushButton(self.group_box)
        self.btn_test.setObjectName("btn_test")
        self.gridLayout_2.addWidget(self.btn_test, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.group_box, 0, 2, 1, 1)
        self.text_browser = QtGui.QTextBrowser(self.centralwidget)
        self.text_browser.setObjectName("text_browser")
        self.gridLayout.addWidget(self.text_browser, 1, 2, 1, 1)
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 555, 21))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtGui.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)
        self.toolbar = QtGui.QToolBar(main_window)
        self.toolbar.setObjectName("toolbar")
        main_window.addToolBar(QtCore.Qt.TopToolBarArea, self.toolbar)
        self.action_quit = QtGui.QAction(main_window)
        self.action_quit.setObjectName("action_quit")
        self.action_save_measurement_data = QtGui.QAction(main_window)
        self.action_save_measurement_data.setObjectName("action_save_measurement_data")
        self.action_settings = QtGui.QAction(main_window)
        self.action_settings.setObjectName("action_settings")
        self.action_connect = QtGui.QAction(main_window)
        self.action_connect.setObjectName("action_connect")
        self.action_disconnect = QtGui.QAction(main_window)
        self.action_disconnect.setEnabled(False)
        self.action_disconnect.setObjectName("action_disconnect")
        self.menu_file.addAction(self.action_connect)
        self.menu_file.addAction(self.action_disconnect)
        self.menu_file.addAction(self.action_settings)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_save_measurement_data)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_quit)
        self.menubar.addAction(self.menu_file.menuAction())
        self.toolbar.addAction(self.action_connect)
        self.toolbar.addAction(self.action_disconnect)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        main_window.setWindowTitle(QtGui.QApplication.translate("main_window", "WFS Application", None, QtGui.QApplication.UnicodeUTF8))
        self.group_box.setTitle(QtGui.QApplication.translate("main_window", "Buttons", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_debug.setText(QtGui.QApplication.translate("main_window", "Debug", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_settings.setText(QtGui.QApplication.translate("main_window", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_test.setText(QtGui.QApplication.translate("main_window", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_file.setTitle(QtGui.QApplication.translate("main_window", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.toolbar.setWindowTitle(QtGui.QApplication.translate("main_window", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.action_quit.setText(QtGui.QApplication.translate("main_window", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_save_measurement_data.setText(QtGui.QApplication.translate("main_window", "Save &Measurement Data", None, QtGui.QApplication.UnicodeUTF8))
        self.action_save_measurement_data.setShortcut(QtGui.QApplication.translate("main_window", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_settings.setText(QtGui.QApplication.translate("main_window", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.action_settings.setShortcut(QtGui.QApplication.translate("main_window", "Ctrl+Alt+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_connect.setText(QtGui.QApplication.translate("main_window", "&Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.action_connect.setShortcut(QtGui.QApplication.translate("main_window", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.action_disconnect.setText(QtGui.QApplication.translate("main_window", "&Disconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.action_disconnect.setShortcut(QtGui.QApplication.translate("main_window", "F2", None, QtGui.QApplication.UnicodeUTF8))

